// vue/src/components/app/index.vue
<template>
    <div class="App">
    <bordered-component position="bottom">
      <header class="App-header">
        <span class="text text-md">Authority Document Card</span>
      </header>
    </bordered-component>

    <Authority />
  </div>
</template>

<script src="./index.js">
</script>

<style lang="scss" src="./index.scss">
</style>

// react/src/components/app/index.jsx
import React from 'react';
import { Bordered } from '../shared';
import Authority from './authority';

import './index.scss';

const App = () => (
  <div className="App">
    <Bordered position="bottom">
      <header className="App-header">
        <span className="text text-md">Authority Document Card</span>
      </header>
    </Bordered>

    <Authority />
  </div>
);

export default App;
