// vue/src/components/app/authority/index.vue
<template>
  <loading-component v-if="isLoading || !Boolean(coreData)" />
  <div v-else>
    <bordered-component position="bottom">
      <AuthorityCore
        :series="coreData.series"
        :catalog_id="coreData.catalog_id"
        :title="coreData.title"
        :subtitle="coreData.subtitle"
        :version="coreData.published_version"
        :section="coreData.section"
        :subsection="coreData.subsection"
        :chapter="coreData.chapter"
        :type="coreData.type"
        :pages="coreData.pages"
        :date="coreData.published_date"
        :commonNames="commonNames"
      />
    </bordered-component>

    <bordered-component position="bottom">
      <container-component size="md">
        <grid-component cols="1">
          <grid-component cols="2">
            <card-component title="Authors">
              <container-component size="sm" class="container-m-s">
                <p
                  v-for="(item, index) in coreData.authors"
                  :key="index"
                  class="text text-md"
                >
                  {{ item.prefix }} {{ item.first_name }}
                  {{ item.middle_initial }} {{ item.last_name }}
                  {{ item.suffix }}
                </p>
              </container-component>
            </card-component>
            <card-component title="Editors">
              <container-component size="sm" class="container-m-s">
                <p
                  v-for="(item, index) in coreData.editors"
                  :key="index"
                  class="text text-md"
                >
                  {{ item.first_name }} {{ item.last_name }}
                </p>
              </container-component>
            </card-component>
          </grid-component>

          <bordered-component>
            <container-component size="md">
              <AuthorityPublish
                :type="coreData.publish_info.epub_type"
                :availability="coreData.publish_info.availability"
                :language="coreData.publish_info.language"
                :websitePublisher="coreData.publish_info.website_publisher"
                :periodicalTitle="coreData.publish_info.periodical_title"
                :volumeIssue="coreData.publish_info.volume_issue"
                :publishedDate="coreData.publish_info.published_date"
                :isbn="coreData.publish_info.isbn"
                :uuid="coreData.publish_info.uuid"
                :searchInfo="coreData.publish_info.search_information"
                :url="coreData.publish_info.url"
                :doi="coreData.publish_info.doi"
              />
            </container-component>
          </bordered-component>
        </grid-component>
      </container-component>
    </bordered-component>
  </div>
</template>

<script src="./index.js">
</script>

// react/src/components/app/authority/index.jsx
import React, { Fragment } from 'react';
import AuthorityCore from './core';
import AuthorityPublish from './publish';
import { Bordered, ContainerMD, Grid, Loading, List } from '../../shared';
import useApi from '../../../utils/hooks/api';

const Authority = () => {
  const [{ data, isLoading }] = useApi.get('/api/authority/core');
  
  if (isLoading) {
    return <Loading />
  }

  const common_names = data.CommonNames['@set'];
  const authors = data.Authors['@set'];
  const editors = data.Editors['@set'];
  const publish_info = data.ADIdentifiers['@set'][0];

  const {
     series,
     catalog_id,
     title,
     subtitle,
     published_version,
     section,
     subsection,
     chapter,
     type,
     pages,
     effective_date: published_date,
  } = data;

  return (
    <Fragment>
      <Bordered position="bottom">
        <AuthorityCore
          series={series}
          catalog_id={catalog_id}
          title={title}
          subtitle={subtitle}
          version={published_version}
          section={section}
          subsection={subsection}
          chapter={chapter}
          type={type}
          pages={pages}
          date={published_date}
          commonNames={common_names.map(q => q.name)}
        />
      </Bordered>

      <Bordered position="bottom">
        <ContainerMD>
          <Grid cols="1">
            <Grid cols="2">
              <List title="Authors"
                    items={authors}
                    itemFormat={q => `${q.first_name ?? ''} ${q.last_name ?? ''}`} />
              <List title="Editors"
                    items={editors}
                    itemFormat={q => `${q.first_name ?? ''} ${q.last_name ?? ''}`} />
            </Grid>

            <Bordered>
              <ContainerMD>
                <AuthorityPublish 
                  type={publish_info.epub_type} 
                  availability={publish_info.availability} 
                  language={publish_info.language} 
                  websitePublisher={publish_info.website_publisher}
                  periodicalTitle={publish_info.periodical_title}
                  volumeIssue={publish_info.volume_issue}
                  publishedDate={publish_info.published_date}
                  isbn={publish_info.isbn}
                  uuid={publish_info.uuid}
                  searchInfo={publish_info.search_information}
                  url={publish_info.url}
                  doi={publish_info.doi}
                  />
              </ContainerMD>
            </Bordered>
          </Grid>
        </ContainerMD>
      </Bordered>
    </Fragment>
  );
};

export default Authority;
